"""
Free and Pro reports.

The two tiers are generated by two functions that share nothing but their
inputs. That separation is deliberate and structural: `generate_free_report`
literally cannot leak Pro content, because it never receives it in a form it
could render. Gating by hiding a section in a template is one CSS mistake away
from giving everything away; gating by never building the object is not.

    generate_free_report(...)  -> Report(tier="free")
    generate_pro_report(...)   -> Report(tier="pro")

Each returns a `Report`, which carries a `tier` field. The website checks that
field, not the content. Anything marked "pro" requires a signed-in member with
an active subscription; anything marked "free" does not.

WHAT GOES IN WHICH TIER
-----------------------
Free  — one flagship finding, the decay-curve chart, a plain-English summary,
        and the last four weeks of the archive.
Pro   — the full ranked Survival Score table across every ticker and indicator
        tested, the raw data as CSV, full methodology notes, and the complete
        archive with score history.

The free tier is not a crippled demo. It carries the week's actual conclusion,
because the conclusion is the part that should be public: a research project
that hides whether its own findings were negative is not a research project.
Pro buys the working, the breadth and the history -- not the answer.
"""

from __future__ import annotations

import datetime as dt
import io
import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd

from config import REPORT_DIR

FREE_ARCHIVE_WEEKS = 4


@dataclass
class Report:
    """One generated report. `tier` is what the site gates on."""

    tier: str                  # "free" | "pro"
    week: int
    published: str
    headline: str
    summary: str
    universe_size: int
    costs_bps: float
    charts: Dict[str, str] = field(default_factory=dict)
    sections: Dict[str, Any] = field(default_factory=dict)
    csv: Optional[str] = None  # Pro only

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# --------------------------------------------------------------------------
# Shared narrative, derived from the data rather than written by hand
# --------------------------------------------------------------------------

def _flagship(scores: pd.DataFrame) -> Dict[str, Any]:
    """The single most interesting row of the week.

    "Most interesting" is the highest score, whatever that score is. On a week
    where nothing clears 4, the flagship finding is that nothing cleared 4 --
    and that gets published as the headline rather than buried.
    """
    if scores.empty:
        return {}
    top = scores.iloc[0]
    return {
        "indicator": top["indicator"],
        "ticker": top["ticker"],
        "score": float(top["score"]),
        "verdict": top["verdict"],
        "out_sample_sharpe_net": _num(top.get("out_sample_sharpe_net")),
        "in_sample_sharpe_gross": _num(top.get("in_sample_sharpe_gross")),
        "pct_windows_positive": _num(top.get("pct_windows_positive")),
        "max_drawdown_net": _num(top.get("max_drawdown_net")),
        "num_trades": int(top.get("num_trades") or 0),
    }


def _num(value):
    if value is None or pd.isna(value):
        return None
    return round(float(value), 6)


def _headline(scores: pd.DataFrame) -> str:
    if scores.empty:
        return "No results this week."

    survived = scores[scores["score"] >= 8.0]
    top = scores.iloc[0]

    if not survived.empty:
        row = survived.iloc[0]
        n = len(survived)
        if n == 1:
            return (f"{row['indicator']} on {row['ticker']} scored "
                    f"{row['score']:.1f} — the only combination to survive.")
        return (f"{n} of {len(scores):,} combinations survived. The best was "
                f"{row['indicator']} on {row['ticker']} at {row['score']:.1f}.")

    if top["score"] >= 6.0:
        return (f"{top['indicator']} on {top['ticker']} led at "
                f"{top['score']:.1f}, positive after costs but beaten by "
                f"simply holding.")

    return (f"Nothing survived. The best of {len(scores)} tested combinations "
            f"was {top['indicator']} on {top['ticker']} at {top['score']:.1f} "
            f"out of 10.")


def _summary(scores: pd.DataFrame) -> str:
    """Plain English, no jargon that is not immediately explained."""
    if scores.empty:
        return "No combinations were tested this week."

    total = len(scores)
    survived = int((scores["score"] >= 8.0).sum())
    positive = int((scores["out_sample_sharpe_net"] > 0).sum())
    median = float(scores["score"].median())

    parts = [
        f"{total:,} indicator-and-stock combinations were tested this week. "
        f"Each was scored from 1 to 10 on whether it still made money on data "
        f"it had never seen, after paying realistic trading costs."
    ]

    if survived:
        parts.append(f"{survived} scored 8 or above, meaning they survived "
                     f"convincingly.")
    else:
        parts.append("None scored 8 or above, so none survived convincingly.")

    # Careful with this sentence. "Profitable" next to "nothing survived"
    # reads as a contradiction unless the difference is spelled out: a small
    # positive Sharpe still loses to simply owning the stock, and that is the
    # comparison that matters.
    # Only claims that the numbers in this table support. An earlier draft
    # asserted that none of these beat buy & hold on the same stock -- true of
    # the single-ticker pilot, but the scoreboard does not compute a per-stock
    # benchmark, so across a full universe it was an unsupported claim in
    # published copy. Removed rather than guessed at.
    parts.append(f"{positive:,} of {total:,} finished with a positive Sharpe "
                 f"ratio after costs, though a positive Sharpe is a low bar "
                 f"and says nothing about whether the rule beat simply owning "
                 f"the stock. The median score was {median:.1f}.")

    parts.append("A low median is the expected result rather than a broken "
                 "test: most published indicator backtests do not subtract "
                 "trading costs or check performance on unseen data, and doing "
                 "both is what removes the apparent edge.")

    # The multiple-comparisons warning. Testing thousands of combinations and
    # then reporting the best of them is how data mining produces findings
    # that do not repeat, and a study this wide has to say so itself.
    if total >= 200 and survived:
        rate = survived / total
        parts.append(
            f"Treat the {survived} survivors with suspicion rather than "
            f"excitement. Testing {total:,} combinations and reporting the best "
            f"of them is precisely how a search produces results that do not "
            f"repeat — at {rate:.1%} of everything tested, this is close to "
            f"what pure chance would throw up. A combination is only "
            f"interesting if it survives again next week, on data that did not "
            f"exist when it was selected."
        )

    return " ".join(parts)


# --------------------------------------------------------------------------
# FREE
# --------------------------------------------------------------------------

SURVIVED_THRESHOLD = 8.0


def _week_in_review(scores: pd.DataFrame,
                    previous: Optional[pd.DataFrame] = None) -> Dict[str, Any]:
    """What this week's run actually found, and how it moved against last week.

    Every figure here is read off the two score tables. Nothing is asserted
    that a reader could not recompute from the published data, because the
    point of a wrap-up is to state the result plainly, not to narrate it.
    """
    survivors = scores[scores["score"] >= SURVIVED_THRESHOLD]
    review: Dict[str, Any] = {
        "combinations_tested": int(len(scores)),
        "survivors": int(len(survivors)),
        "median_score": round(float(scores["score"].median()), 2),
        "positive_after_costs": int((scores["out_sample_sharpe_net"] > 0).sum()),
        "by_indicator": {
            str(name): {
                "median_score": round(float(group["score"].median()), 2),
                "survivors": int((group["score"] >= SURVIVED_THRESHOLD).sum()),
            }
            for name, group in scores.groupby("indicator")
        },
    }

    if previous is None or previous.empty:
        review["change"] = None
        review["change_note"] = (
            "This is the first week on record for this universe, so there is "
            "nothing to compare it against yet. The comparison is the whole "
            "point, and it starts next week."
        )
        return review

    # Only compare like with like.
    #
    # Week 1 here was a single-ticker pilot and week 2 was 827 companies.
    # Reporting that "the median score fell 1.3" across those two is a
    # meaningless number that reads like a finding, which is precisely the
    # kind of thing this project exists to not do. If the two runs do not
    # cover substantially the same universe, the comparison is refused and
    # the reason is stated.
    now_tickers = set(scores["ticker"])
    prev_tickers = set(previous["ticker"])
    shared = now_tickers & prev_tickers
    comparable = bool(shared) and len(shared) >= 0.8 * max(len(now_tickers),
                                                           len(prev_tickers))
    if not comparable:
        review["change"] = None
        review["change_note"] = (
            f"Last week's run covered {len(prev_tickers)} "
            f"{'company' if len(prev_tickers) == 1 else 'companies'} and this "
            f"week's covered {len(now_tickers)}, so the two are not the same "
            f"test and no week-on-week comparison is drawn. Comparing them "
            f"would produce a number that looks like a finding and is not one. "
            f"The comparison resumes once two consecutive weeks cover the same "
            f"universe."
        )
        return review

    prev_survivors = previous[previous["score"] >= SURVIVED_THRESHOLD]
    prev_median = round(float(previous["score"].median()), 2)

    # The question that matters: of the combinations that survived last week,
    # how many survived again? A rule that only survives once is what noise
    # looks like.
    prev_pairs = set(zip(prev_survivors["indicator"], prev_survivors["ticker"]))
    now_pairs = set(zip(survivors["indicator"], survivors["ticker"]))
    repeated = sorted(prev_pairs & now_pairs)

    review["change"] = {
        "survivors_last_week": len(prev_pairs),
        "survivors_this_week": len(now_pairs),
        "repeated": [{"indicator": i, "ticker": t} for i, t in repeated],
        "repeat_count": len(repeated),
        "median_score_last_week": prev_median,
        "median_score_change": round(review["median_score"] - prev_median, 2),
    }

    # How far apart the two runs actually are.
    #
    # A repeat rate only means something if the second test saw meaningfully
    # new data. Two runs three days apart share almost their whole window, so
    # "10 of 12 survived again" is close to arithmetic rather than evidence.
    # Reporting the repeat rate without this is the sort of number that reads
    # as confirmation and is not.
    gap_days = None
    try:
        prev_published = str(previous["published"].iloc[0])
        now_published = str(scores["published"].iloc[0]) if "published" in scores.columns else None
        if now_published:
            gap_days = (dt.date.fromisoformat(now_published)
                        - dt.date.fromisoformat(prev_published)).days
    except Exception:
        gap_days = None
    review["change"]["days_since_last_run"] = gap_days

    overlap_caveat = ""
    if gap_days is not None and gap_days < 7:
        overlap_caveat = (
            f" These two runs are only {gap_days} day"
            f"{'' if gap_days == 1 else 's'} apart, so they were scored on "
            f"almost the same data. A combination repeating across windows "
            f"that overlap this heavily is close to arithmetic rather than "
            f"evidence, and this comparison should not be read as one until "
            f"the runs are a full week apart.")

    if not prev_pairs:
        note = ("Nothing survived last week, so there was nothing that could "
                "repeat.")
    elif not repeated:
        note = (f"None of last week's {len(prev_pairs)} survivors survived "
                f"again. That is what a list of coincidences looks like when "
                f"it is re-tested, and it is the result this project expects "
                f"more often than not.")
    else:
        note = (f"{len(repeated)} of last week's {len(prev_pairs)} survivors "
                f"survived again. Repeating twice is weak evidence, not "
                f"strong: with this many combinations tested, some will "
                f"repeat by chance alone.")
    review["change_note"] = note + overlap_caveat
    return review


def _week_ahead(scores: pd.DataFrame) -> Dict[str, Any]:
    """What next week's data will test about this week's claims.

    Deliberately NOT a market outlook. This project does not forecast prices,
    and saying what a stock might do next week would be exactly the kind of
    tip it refuses to give at any price. What can honestly be written in
    advance is which of this week's results are checkable next week, and what
    result would count as being wrong.
    """
    survivors = (scores[scores["score"] >= SURVIVED_THRESHOLD]
                 .sort_values("score", ascending=False))

    watch = [
        {
            "indicator": str(r["indicator"]),
            "ticker": str(r["ticker"]),
            "score": round(float(r["score"]), 1),
            "out_sample_sharpe_net": (
                None if pd.isna(r["out_sample_sharpe_net"])
                else round(float(r["out_sample_sharpe_net"]), 3)),
        }
        for _, r in survivors.head(10).iterrows()
    ]

    return {
        "claims_to_recheck": watch,
        "claims_total": int(len(survivors)),
        "test": (
            "Every one of these is re-scored next week on a window that "
            "includes days which did not exist when the score was assigned. "
            "No result is re-used and nothing is carried over."
        ),
        "what_would_be_wrong": (
            "If these were real, most should still clear 8 next week. If they "
            "were noise, most should fall away. Either outcome is published, "
            "and the second is the more likely one: test thousands of "
            "combinations and a handful will look good by accident."
        ),
        "not_a_forecast": (
            "This is a list of claims being checked, not a list of stocks to "
            "buy. Nothing here is a prediction about any company, and a high "
            "Survival Score is a statement about a rule's past behaviour "
            "after costs, not about what a share price will do next."
        ),
    }


def generate_free_report(
    scores: pd.DataFrame,
    week: int,
    universe: List[str],
    costs_bps: float,
    charts: Optional[Dict[str, str]] = None,
    archive_weeks: Optional[pd.DataFrame] = None,
    published: Optional[str] = None,
    previous: Optional[pd.DataFrame] = None,
) -> Report:
    """The public report.

    Receives the full scores table but publishes only the flagship row from
    it. The full table never enters the returned object, so there is nothing
    for a template mistake to expose.
    """
    recent = []
    if archive_weeks is not None and not archive_weeks.empty:
        recent = (archive_weeks.head(FREE_ARCHIVE_WEEKS)
                  .to_dict("records"))

    return Report(
        tier="free",
        week=week,
        published=published or dt.date.today().isoformat(),
        headline=_headline(scores),
        summary=_summary(scores),
        universe_size=len(universe),
        costs_bps=costs_bps,
        charts=dict(charts or {}),
        sections={
            "flagship": _flagship(scores),
            "combinations_tested": int(len(scores)),
            # The wrap-up and the week-ahead are free on purpose. Whether last
            # week's findings held up is the result, and the result is the part
            # that belongs in public.
            "week_in_review": _week_in_review(scores, previous),
            "week_ahead": _week_ahead(scores),
            "archive": recent,
            "archive_weeks_shown": FREE_ARCHIVE_WEEKS,
            "upgrade_note": (
                "The full ranked table across every stock and indicator "
                "tested, the raw data, and the complete archive are available "
                "to Pro members."
            ),
        },
    )


# --------------------------------------------------------------------------
# PRO
# --------------------------------------------------------------------------

PRO_TABLE_COLUMNS = [
    "indicator", "ticker", "score", "verdict",
    "performance", "consistency", "drawdown", "raw_score", "capped_by",
    "in_sample_sharpe_gross", "out_sample_sharpe_gross",
    "out_sample_sharpe_net", "max_drawdown_net", "pct_windows_positive",
    "n_windows", "num_trades", "time_in_market", "cost_paid",
]


def generate_pro_report(
    scores: pd.DataFrame,
    week: int,
    universe: List[str],
    costs_bps: float,
    charts: Optional[Dict[str, str]] = None,
    archive_weeks: Optional[pd.DataFrame] = None,
    score_history: Optional[pd.DataFrame] = None,
    published: Optional[str] = None,
    previous: Optional[pd.DataFrame] = None,
) -> Report:
    """The members' report: the full table, the raw data, and the history."""
    columns = [c for c in PRO_TABLE_COLUMNS if c in scores.columns]
    table = scores[columns].copy()

    buffer = io.StringIO()
    table.to_csv(buffer, index=False)

    return Report(
        tier="pro",
        week=week,
        published=published or dt.date.today().isoformat(),
        headline=_headline(scores),
        summary=_summary(scores),
        universe_size=len(universe),
        costs_bps=costs_bps,
        charts=dict(charts or {}),
        csv=buffer.getvalue(),
        sections={
            "flagship": _flagship(scores),
            "table": table.to_dict("records"),
            "combinations_tested": int(len(scores)),
            "week_in_review": _week_in_review(scores, previous),
            "week_ahead": _week_ahead(scores),
            "universe": sorted(universe),
            "archive": (archive_weeks.to_dict("records")
                        if archive_weeks is not None and not archive_weeks.empty
                        else []),
            "score_history": (score_history.to_dict("records")
                              if score_history is not None
                              and not score_history.empty else []),
            "methodology": METHODOLOGY_NOTES,
        },
    )


METHODOLOGY_NOTES = [
    "Signals are computed on the full price history, then sliced into train "
    "and test. No parameter is chosen using test-period data — the test half "
    "is measured once, never searched.",

    "Positions are shifted forward one bar before returns are applied. A "
    "signal from Monday's close can only be traded at Monday's close, so the "
    "first return it can earn is Monday to Tuesday. Omitting this is the most "
    "common backtest error and is worth one to three points of Sharpe.",

    "Costs are charged on turnover: |change in position| × the per-side rate. "
    "A long-to-short flip pays twice.",

    "Walk-forward windows train on three years and test on the following "
    "year, rolling forward annually. The consistency component uses the share "
    "of those windows that were positive, not their mean — a rule that earned "
    "everything in one year should not look steady.",

    "The Survival Score is a weighted composite: 60% out-of-sample net Sharpe, "
    "25% walk-forward consistency, 15% drawdown resilience, with hard caps for "
    "strategies that lost money or barely traded. Every constant is documented "
    "in scoring.py and can be changed and recomputed.",

    "The cost model applies one figure to every stock. That is roughly right "
    "for large caps and materially too optimistic for smaller names, where "
    "real spreads are often several times wider. High scores concentrated in "
    "small or recently-listed companies should be read as a warning about the "
    "cost assumption before they are read as a finding.",

    "Universe uses current index membership, so companies delisted along the "
    "way are absent. This flatters absolute returns; it affects the in-sample "
    "versus out-of-sample comparison far less, which is why that comparison is "
    "the headline rather than the absolute figure.",
]


# --------------------------------------------------------------------------
# Writing
# --------------------------------------------------------------------------

def write_report(report: Report, outdir: Optional[Path] = None) -> Dict[str, Path]:
    """Write a report to disk. Pro reports also emit their CSV.

    Filenames carry the tier, so a Pro artefact is never mistaken for a public
    one when copying files to the website.
    """
    outdir = outdir or REPORT_DIR
    outdir.mkdir(parents=True, exist_ok=True)
    stem = f"week{report.week:02d}_{report.tier}"

    payload = report.to_dict()
    csv_text = payload.pop("csv", None)

    written = {}
    json_path = outdir / f"{stem}.json"
    json_path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    written["json"] = json_path

    if csv_text:
        csv_path = outdir / f"{stem}_scores.csv"
        csv_path.write_text(csv_text, encoding="utf-8")
        written["csv"] = csv_path

    return written
