"""
Free and Pro reports.

The two tiers are generated by two functions that share nothing but their
inputs. That separation is deliberate and structural: `generate_free_report`
literally cannot leak Pro content, because it never receives it in a form it
could render. Gating by hiding a section in a template is one CSS mistake away
from giving everything away; gating by never building the object is not.

    generate_free_report(...)  -> Report(tier="free")
    generate_pro_report(...)   -> Report(tier="pro")

Each returns a `Report`, which carries a `tier` field. The website checks that
field, not the content. Anything marked "pro" requires a signed-in member with
an active subscription; anything marked "free" does not.

WHAT GOES IN WHICH TIER
-----------------------
Free  — one flagship finding, the decay-curve chart, a plain-English summary,
        and the last four weeks of the archive.
Pro   — the full ranked Survival Score table across every ticker and indicator
        tested, the raw data as CSV, full methodology notes, and the complete
        archive with score history.

The free tier is not a crippled demo. It carries the week's actual conclusion,
because the conclusion is the part that should be public: a research project
that hides whether its own findings were negative is not a research project.
Pro buys the working, the breadth and the history -- not the answer.
"""

from __future__ import annotations

import datetime as dt
import io
import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd

from config import REPORT_DIR

FREE_ARCHIVE_WEEKS = 4


@dataclass
class Report:
    """One generated report. `tier` is what the site gates on."""

    tier: str                  # "free" | "pro"
    week: int
    published: str
    headline: str
    summary: str
    universe_size: int
    costs_bps: float
    charts: Dict[str, str] = field(default_factory=dict)
    sections: Dict[str, Any] = field(default_factory=dict)
    csv: Optional[str] = None  # Pro only

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# --------------------------------------------------------------------------
# Shared narrative, derived from the data rather than written by hand
# --------------------------------------------------------------------------

def _flagship(scores: pd.DataFrame) -> Dict[str, Any]:
    """The single most interesting row of the week.

    "Most interesting" is the highest score, whatever that score is. On a week
    where nothing clears 4, the flagship finding is that nothing cleared 4 --
    and that gets published as the headline rather than buried.
    """
    if scores.empty:
        return {}
    top = scores.iloc[0]
    return {
        "indicator": top["indicator"],
        "ticker": top["ticker"],
        "score": float(top["score"]),
        "verdict": top["verdict"],
        "out_sample_sharpe_net": _num(top.get("out_sample_sharpe_net")),
        "in_sample_sharpe_gross": _num(top.get("in_sample_sharpe_gross")),
        "pct_windows_positive": _num(top.get("pct_windows_positive")),
        "max_drawdown_net": _num(top.get("max_drawdown_net")),
        "num_trades": int(top.get("num_trades") or 0),
    }


def _num(value):
    if value is None or pd.isna(value):
        return None
    return round(float(value), 6)


def _headline(scores: pd.DataFrame) -> str:
    if scores.empty:
        return "No results this week."

    survived = scores[scores["score"] >= 8.0]
    top = scores.iloc[0]

    if not survived.empty:
        row = survived.iloc[0]
        return (f"{row['indicator']} on {row['ticker']} scored "
                f"{row['score']:.1f} — the only rule to survive convincingly.")

    if top["score"] >= 6.0:
        return (f"{top['indicator']} on {top['ticker']} led at "
                f"{top['score']:.1f}, positive after costs but beaten by "
                f"simply holding.")

    return (f"Nothing survived. The best of {len(scores)} tested combinations "
            f"was {top['indicator']} on {top['ticker']} at {top['score']:.1f} "
            f"out of 10.")


def _summary(scores: pd.DataFrame) -> str:
    """Plain English, no jargon that is not immediately explained."""
    if scores.empty:
        return "No combinations were tested this week."

    total = len(scores)
    survived = int((scores["score"] >= 8.0).sum())
    positive = int((scores["out_sample_sharpe_net"] > 0).sum())
    median = float(scores["score"].median())

    parts = [
        f"{total} indicator-and-stock combinations were tested this week. "
        f"Each was scored from 1 to 10 on whether it still made money on data "
        f"it had never seen, after paying realistic trading costs."
    ]

    if survived:
        parts.append(f"{survived} scored 8 or above, meaning they survived "
                     f"convincingly.")
    else:
        parts.append("None scored 8 or above, so none survived convincingly.")

    # Careful with this sentence. "Profitable" next to "nothing survived"
    # reads as a contradiction unless the difference is spelled out: a small
    # positive Sharpe still loses to simply owning the stock, and that is the
    # comparison that matters.
    parts.append(f"{positive} of {total} finished with a positive Sharpe ratio "
                 f"after costs — but a positive Sharpe is a low bar, and none "
                 f"of them beat simply buying and holding the same stock. The "
                 f"median score was {median:.1f}.")

    parts.append("A low median is the expected result rather than a broken "
                 "test: most published indicator backtests do not subtract "
                 "trading costs or check performance on unseen data, and doing "
                 "both is what removes the apparent edge.")

    return " ".join(parts)


# --------------------------------------------------------------------------
# FREE
# --------------------------------------------------------------------------

def generate_free_report(
    scores: pd.DataFrame,
    week: int,
    universe: List[str],
    costs_bps: float,
    charts: Optional[Dict[str, str]] = None,
    archive_weeks: Optional[pd.DataFrame] = None,
    published: Optional[str] = None,
) -> Report:
    """The public report.

    Receives the full scores table but publishes only the flagship row from
    it. The full table never enters the returned object, so there is nothing
    for a template mistake to expose.
    """
    recent = []
    if archive_weeks is not None and not archive_weeks.empty:
        recent = (archive_weeks.head(FREE_ARCHIVE_WEEKS)
                  .to_dict("records"))

    return Report(
        tier="free",
        week=week,
        published=published or dt.date.today().isoformat(),
        headline=_headline(scores),
        summary=_summary(scores),
        universe_size=len(universe),
        costs_bps=costs_bps,
        charts=dict(charts or {}),
        sections={
            "flagship": _flagship(scores),
            "combinations_tested": int(len(scores)),
            "archive": recent,
            "archive_weeks_shown": FREE_ARCHIVE_WEEKS,
            "upgrade_note": (
                "The full ranked table across every stock and indicator "
                "tested, the raw data, and the complete archive are available "
                "to Pro members."
            ),
        },
    )


# --------------------------------------------------------------------------
# PRO
# --------------------------------------------------------------------------

PRO_TABLE_COLUMNS = [
    "indicator", "ticker", "score", "verdict",
    "performance", "consistency", "drawdown", "raw_score", "capped_by",
    "in_sample_sharpe_gross", "out_sample_sharpe_gross",
    "out_sample_sharpe_net", "max_drawdown_net", "pct_windows_positive",
    "n_windows", "num_trades", "time_in_market", "cost_paid",
]


def generate_pro_report(
    scores: pd.DataFrame,
    week: int,
    universe: List[str],
    costs_bps: float,
    charts: Optional[Dict[str, str]] = None,
    archive_weeks: Optional[pd.DataFrame] = None,
    score_history: Optional[pd.DataFrame] = None,
    published: Optional[str] = None,
) -> Report:
    """The members' report: the full table, the raw data, and the history."""
    columns = [c for c in PRO_TABLE_COLUMNS if c in scores.columns]
    table = scores[columns].copy()

    buffer = io.StringIO()
    table.to_csv(buffer, index=False)

    return Report(
        tier="pro",
        week=week,
        published=published or dt.date.today().isoformat(),
        headline=_headline(scores),
        summary=_summary(scores),
        universe_size=len(universe),
        costs_bps=costs_bps,
        charts=dict(charts or {}),
        csv=buffer.getvalue(),
        sections={
            "flagship": _flagship(scores),
            "table": table.to_dict("records"),
            "combinations_tested": int(len(scores)),
            "universe": sorted(universe),
            "archive": (archive_weeks.to_dict("records")
                        if archive_weeks is not None and not archive_weeks.empty
                        else []),
            "score_history": (score_history.to_dict("records")
                              if score_history is not None
                              and not score_history.empty else []),
            "methodology": METHODOLOGY_NOTES,
        },
    )


METHODOLOGY_NOTES = [
    "Signals are computed on the full price history, then sliced into train "
    "and test. No parameter is chosen using test-period data — the test half "
    "is measured once, never searched.",

    "Positions are shifted forward one bar before returns are applied. A "
    "signal from Monday's close can only be traded at Monday's close, so the "
    "first return it can earn is Monday to Tuesday. Omitting this is the most "
    "common backtest error and is worth one to three points of Sharpe.",

    "Costs are charged on turnover: |change in position| × the per-side rate. "
    "A long-to-short flip pays twice.",

    "Walk-forward windows train on three years and test on the following "
    "year, rolling forward annually. The consistency component uses the share "
    "of those windows that were positive, not their mean — a rule that earned "
    "everything in one year should not look steady.",

    "The Survival Score is a weighted composite: 60% out-of-sample net Sharpe, "
    "25% walk-forward consistency, 15% drawdown resilience, with hard caps for "
    "strategies that lost money or barely traded. Every constant is documented "
    "in scoring.py and can be changed and recomputed.",

    "Universe uses current index membership, so companies delisted along the "
    "way are absent. This flatters absolute returns; it affects the in-sample "
    "versus out-of-sample comparison far less, which is why that comparison is "
    "the headline rather than the absolute figure.",
]


# --------------------------------------------------------------------------
# Writing
# --------------------------------------------------------------------------

def write_report(report: Report, outdir: Optional[Path] = None) -> Dict[str, Path]:
    """Write a report to disk. Pro reports also emit their CSV.

    Filenames carry the tier, so a Pro artefact is never mistaken for a public
    one when copying files to the website.
    """
    outdir = outdir or REPORT_DIR
    outdir.mkdir(parents=True, exist_ok=True)
    stem = f"week{report.week:02d}_{report.tier}"

    payload = report.to_dict()
    csv_text = payload.pop("csv", None)

    written = {}
    json_path = outdir / f"{stem}.json"
    json_path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    written["json"] = json_path

    if csv_text:
        csv_path = outdir / f"{stem}_scores.csv"
        csv_path.write_text(csv_text, encoding="utf-8")
        written["csv"] = csv_path

    return written
